### PR TITLE
Update Readme to work online without downloads

### PR DESCRIPTION
**Pull request by SantiParris8**
Added the necessary jupyter steps to use this tool online without any local downloads.

### CODE REVIEW

**Comment by SantiParris8** [comment]
Created pull request. Tested functionality working perfectly.

**Comment by thomasarmel** [comment]
Hi,
Thanks for your contribution.
However I'm not sure that all these details are needed. You can just tell the reader how to mount a Google Drive directory into his filesystem.
So it doesn't "work online": it actually download the movie locally, but directly into the Google Drive directory.

Btw there is a README for each version, CLI and GUI: https://github.com/thomasarmel/uqload_downloader/tree/main/cli

**Comment by SantiParris8** [comment]
No problem.
Would you like me to maybe update only the CLI guide and with less steps?
Regards.

**Comment by SantiParris8** [comment]
Awaiting for your response to close this merge.

**Comment by thomasarmel** [comment]
Could you explain to me why you want to give more precisions about downloading into a Google Drive directory?
Do you have a specific use case in mind?

**Comment by SantiParris8** [comment]
Sure, this approach can be used in windows and in any mobile (This together
means 80% of the internet traffic).
Also, the steps on mounting the drive might be really easy but you are
providing a way for anyone with minimal technical abilities to download the
videos.
Regards.

**Comment by thomasarmel** [comment]
Sorry but I really don't understand.
"this approach can be used in windows and in any mobile" what do you mean exactly?
And more generally how is it relevant to add precision about mounting a Google Drive directory? Do you have a specific use case in mind that would need the file to be downloaded into Google Drive?

**Pull request closed without merging**
